name = "GeoFacetMakie"
uuid = "f2e9801d-a43b-4ab5-b898-52709f6fb569"
authors = ["arnold-c <24391445+arnold-c@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
DataFrames = "1"
Makie = "0.24"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
