name = "GeoFacetMakie"
uuid = "f2e9801d-a43b-4ab5-b898-52709f6fb569"
authors = ["arnold-c <24391445+arnold-c@users.noreply.github.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.13.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
